version: '3'
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    expose:
      - 3306
    #ports:
      #- 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=233466
      - MYSQL_USER=test
      - MYSQL_PASS=pass
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
